### ISSUE TITLE
Remap fails after split_events

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-python#558]
When running remodeler from the command line in some cases using the remodeler to remap columns results in the following error:

```
Traceback (most recent call last):
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\Lib\site-packages\hed\tools\remodeling\cli\run_remodel.py", line 120, in <module>
    main()
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\Lib\site-packages\hed\tools\remodeling\cli\run_remodel.py", line 113, in main
    run_bids_ops(dispatch, args)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\Lib\site-packages\hed\tools\remodeling\cli\run_remodel.py", line 76, in run_bids_ops
    df = dispatch.run_operations(events_obj.file_path, sidecar=sidecar, verbose=args.verbose)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\hed\tools\remodeling\dispatcher.py", line 115, in run_operations
    df = operation.do_op(self, df, file_path, sidecar=sidecar)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\hed\tools\remodeling\operations\remap_columns_op.py", line 70, in do_op
    df_new, missing = self.key_map.remap(df)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\hed\tools\analysis\key_map.py", line 93, in remap
    remove_quotes(df_new)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\hed\tools\util\data_util.py", line 257, in remove_quotes
    df.iloc[:, index] = df.iloc[:, index].str.replace('"', '')
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\pandas\core\generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\pandas\core\accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\pandas\core\strings\accessor.py", line 181, in __init__
[events_and_remodelfile.zip](https://github.com/hed-standard/hed-python/files/10084223/events_and_remodelfile.zip)

    self._inferred_dtype = self._validate(data)
  File "C:\Users\$USER\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\pandas\core\strings\accessor.py", line 235, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
```

It only happens after the split_event operation runs before. It looks like split events makes changes to the index that the remap operation cannot handle. Running the remap operation alone does not cause the error. Other operations (delete_columns, rename_columns) also do not cause an error.

Full event file and remodeler instruction is included.

**Comment by VisLab** [comment]
I believe this is fixed in HEDTools [version: 0.1.0+171.geb7d925 date: 2022-12-22T09:32:14-0600]
on the develop branch and on https://hedtools.ucsd.edu/hed_dev.

If you find it is not fixed, please reopen this issue.
