### ISSUE TITLE
Backup does not automatically exclude remodel file

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-python#560]
When I try to create a second, named backup I get the following error:

```
`(hedtools) C:\Users\AppData\Local\Continuum\anaconda3\envs\hedtools\Lib\site-packages\hed\tools\remodeling\cli>python run_remodel_backup.py "C:\Users\Documents\ben_openneurodatasets\ds001894" -n "step1_complete"
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\hedtools\Lib\site-packages\hed\tools\remodeling\cli\run_remodel_backup.py", line 46, in <module>
    main()
  File "C:\Users\\AppData\Local\Continuum\anaconda3\envs\hedtools\Lib\site-packages\hed\tools\remodeling\cli\run_remodel_backup.py", line 42, in main
    backup_man.create_backup(file_list, backup_name=args.backup_name, verbose=args.verbose)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\site-packages\hed\tools\remodeling\backup_manager.py", line 53, in create_backup
    shutil.copy2(x, backup_file)
  File "C:\Users\\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\hedtools\lib\shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Documents\\ben_openneurodatasets\\ds001894\\derivatives\\remodel\\backups\\step1_complete\\backup_root\\derivatives\\remodel\\backups\\default_back\\backup_root\\sub-001\\ses-T1\\func\\sub-001_ses-T1_task-AANonWord_run-01_events.tsv'
```

It seems it tries to backup the default backup. The backup runs when I specify derivatives as an exclude dir, but from the documentation I understand that the `remodel` directory should have already been excluded.

**Comment by VisLab** [comment]
Fixed in HEDTools [version: 0.1.0+171.geb7d925 date: 2022-12-22T09:32:14-0600]
on the develop branch and on https://hedtools.ucsd.edu/hed_dev.
